# GitHub Account Switcher
# Short arguments: a (aiwithr) or r (raqueeb)
# Usage: .\switch.ps1 a  OR  .\switch.ps1 r

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("a", "r", "A", "R", "status")]
    [string]$Account
)

$SSH_DIR = "$env:USERPROFILE\.ssh"
$CONFIG_FILE = "$SSH_DIR\config"

# Normalize to lowercase
if ($Account) { $Account = $Account.ToLower() }

# Check current account from SSH config (which key is assigned to github.com)
$currentConfig = Get-Content $CONFIG_FILE -Raw -ErrorAction SilentlyContinue
$lines = $currentConfig -split "`n"
$inGithubBlock = $false
$githubKey = ""
foreach ($line in $lines) {
    $line = $line.Trim()
    if ($line -match '^Host\s+github\.com$') { $inGithubBlock = $true; continue }
    if ($line -match '^Host\s+' -and $inGithubBlock) { break }
    if ($inGithubBlock -and $line -match '^IdentityFile\s+(.+)$') {
        $githubKey = $matches[1]
        break
    }
}
$currentAccount = if ($githubKey -match 'aiwithr') { "a" } else { "r" }

# Display current status if no account specified
if (-not $Account -or $Account -eq "status") {
    Write-Host ""
    Write-Host "======================================" -ForegroundColor Yellow
    Write-Host "  Current: $(if ($currentAccount -eq 'a') { 'aiwithr (a)' } else { 'raqueeb (r)' })" -ForegroundColor Cyan
    Write-Host "======================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Usage:"
    Write-Host "  .\switch.ps1 a   (switch to aiwithr)" -ForegroundColor Green
    Write-Host "  .\switch.ps1 r   (switch to raqueeb)" -ForegroundColor Green
    Write-Host ""
    exit 0
}

# Check if already on the requested account
if ($Account -eq $currentAccount) {
    $name = if ($Account -eq 'a') { 'aiwithr' } else { 'raqueeb' }
    Write-Host "Already on: $name" -ForegroundColor Yellow
    exit 0
}

# Generate SSH config based on selected account
if ($Account -eq "a") {
    $config = @"
# GitHub SSH Config - Generated by switch.ps1
# Active Account: aiwithr

# aiwithr account (default for github.com)
Host github.com
    HostName github.com
    User git
    IdentityFile $SSH_DIR\id_ed25519_aiwithr

# raqueeb account (use raqueeb.github.com)
Host raqueeb.github.com
    HostName github.com
    User git
    IdentityFile $SSH_DIR\id_ed25519_raqueeb
"@
} else {
    $config = @"
# GitHub SSH Config - Generated by switch.ps1
# Active Account: raqueeb

# raqueeb account (default for github.com)
Host github.com
    HostName github.com
    User git
    IdentityFile $SSH_DIR\id_ed25519_raqueeb

# aiwithr account (use aiwithr.github.com)
Host aiwithr.github.com
    HostName github.com
    User git
    IdentityFile $SSH_DIR\id_ed25519_aiwithr
"@
}

Set-Content -Path $CONFIG_FILE -Value $config -Force

$name = if ($Account -eq 'a') { 'aiwithr' } else { 'raqueeb' }
Write-Host ""
Write-Host "======================================" -ForegroundColor Green
Write-Host "  Switched to: $name" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Green
Write-Host ""
Write-Host "github.com now uses $name SSH key"
Write-Host ""
Write-Host "To clone a specific account repo:"
Write-Host "  git clone git@raqueeb.github.com:user/repo.git"
Write-Host "  git clone git@aiwithr.github.com:user/repo.git"